name: App with Github Actions, wbc

on:
  # workflow_dispatch
  push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make application.properties
      run: |
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.PROPERTIES }}" > ./application.properties
      shell: bash

    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build -x test
      # env:
        # GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: build/libs

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}
    
    - uses: actions/checkout@v4
      with:
        repository: linkpond/wbc-manifest
        ref: main
        token: ${{ secrets.TOKEN }}
    
    - name: Set up Image
      run: |
        sed -i "s%image: ${{ secrets.DOCKERHUB_USERNAME }}/wbc:[A-z0-9]*%image: ${{ secrets.DOCKERHUB_USERNAME }}/wbc:${{ github.sha }}%" ./manifest/wbc-app.yaml
    
    - name: Commit and push changes
      run: |
        git config --local user.email "linkpond0629@gmail.com"
        git config --local user.name "linkpond"
        git add .
        git commit -m "Update nginx image to latest"
        git push
